title: IOT security blog
description: "Tomas Vanagas blog for malware enthusiasts."
author:
  name: "Tomas"
  email: "tomas.vanagas@knf.vu.lt"
  url: "http://tomasvanagas.ml"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Tomas Vanagas"
year : "2019"
